import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { HOOK_COVERAGE } from "../test/harness/coverage.js";
import { VENDORED_HOST_VERSION } from "../test/harness/mock-host.js";
import { flushAndReadRawLines, flushAndReadSpans, runScenario, cleanupTracerTmp } from "../test/harness/scenario.js";

/**
 * Regenerate the committed sample corpus under `samples/`.
 *
 * Runs the same full-turn scenario the E2E suite drives, then writes:
 *   - samples/full-turn.otlp.ndjson  — every span from one turn, as exported
 *   - samples/spans/<hook>.json       — one decoded sample span per hook
 *   - samples/coverage.json           — the coverage manifest + host version
 *
 * `npm run samples` runs this; the samples double as the E2E golden output.
 */
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const samplesDir = join(repoRoot, "samples");
const spansDir = join(samplesDir, "spans");

function slug(name: string): string {
  return name.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "");
}

async function main(): Promise<void> {
  mkdirSync(spansDir, { recursive: true });

  const r = await runScenario({
    sessionKeySuffix: "samples",
    includeCompaction: true,
    includeToolError: true,
  });

  const rawLines = (await flushAndReadRawLines()).filter((line) => line.includes("samples"));
  writeFileSync(join(samplesDir, "full-turn.otlp.ndjson"), rawLines.join("\n") + "\n", "utf8");

  const spans = (await flushAndReadSpans()).filter(
    (s) => s.attributes["openclaw.session.key"] === r.sessionKey
  );

  let written = 0;
  for (const c of HOOK_COVERAGE) {
    const span = spans.find((s) => s.name === c.span);
    if (!span) continue;
    const doc = {
      hook: c.hook,
      span: c.span,
      conversationHook: c.conversationHook ?? false,
      minHost: c.minHost,
      legacyAliases: c.legacyAliases,
      fieldMapping: c.fieldMapping,
      notes: c.notes,
      sampleSpan: {
        name: span.name,
        kind: span.kind,
        traceId: span.traceId,
        spanId: span.spanId,
        parentSpanId: span.parentSpanId,
        status: span.status,
        attributes: span.attributes,
      },
    };
    writeFileSync(join(spansDir, `${slug(c.hook)}.json`), JSON.stringify(doc, null, 2) + "\n", "utf8");
    written++;
  }

  writeFileSync(
    join(samplesDir, "coverage.json"),
    JSON.stringify(
      {
        _comment: "Generated by `npm run samples`. Do not edit by hand.",
        hostVersion: VENDORED_HOST_VERSION,
        hookCount: HOOK_COVERAGE.length,
        hooks: HOOK_COVERAGE,
      },
      null,
      2
    ) + "\n",
    "utf8"
  );

  cleanupTracerTmp();
  console.log(
    `Wrote ${written} hook sample spans, full-turn NDJSON (${rawLines.length} lines), and coverage.json to samples/`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
